version: '3'
services:
  currency_db:
    hostname: mydb
    image: mysql:latest
    container_name: currency_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currencyDB
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - currency_network
  application:
    image: currency:latest
    depends_on:
      - currency_db
    environment:
      DB_HOSTNAME: mydb
      DB_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - currency_network
volumes:
  db_data:

networks:
  currency_network:
